# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-30 16:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensor01', '0002_rawdata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='rawData',
            new_name='rawDatas',
        ),
    ]
