# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-30 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor01', '0003_auto_20170731_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawdatas',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
